import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { PolicyMode } from "../policy.js";
import { SCOPES, Scope } from "../scopes.js";
import type { McpRuntime } from "../mcp.js";
import {
  registerBrowserCdpConnectTool,
  registerBrowserClickTool,
  registerBrowserConsoleTool,
  registerBrowserFillTool,
  registerBrowserNavigateTool,
  registerBrowserNetworkTool,
  registerBrowserPageListTool,
  registerBrowserPageSelectTool,
  registerBrowserPressKeyTool,
  registerBrowserScreenshotTool,
  registerBrowserSessionCloseTool,
  registerBrowserSessionCreateTool,
  registerBrowserSessionListTool,
  registerBrowserSnapshotTool,
  registerBrowserTypeTool,
  registerBrowserWaitTool,
} from "./browser.js";
import {
  registerRemoteWorkerCallTool,
  registerRemoteWorkerHealthTool,
  registerRemoteWorkerListTool,
  registerRemoteWorkerToolsTool,
} from "./remote-worker.js";
import {
  registerDesktopHotkeyTool,
  registerDesktopKeyPressTool,
  registerDesktopMouseClickTool,
  registerDesktopMouseMoveTool,
  registerDesktopMousePositionTool,
  registerDesktopTextTypeTool,
} from "./desktop.js";
import {
  registerHashTool,
  registerListDirTool,
  registerReadFileRangeTool,
  registerReadFileTool,
  registerReadManyTool,
  registerStatManyTool,
  registerStatTool,
  registerTreeTool,
  registerWriteFileTool,
} from "./files.js";
import {
  registerApplyPatchTool,
  registerCopyTool,
  registerDeleteTool,
  registerGitCommitTool,
  registerGitDiffTool,
  registerGitStatusTool,
  registerMkdirTool,
  registerMoveTool,
  registerRollbackBackupTool,
  registerSearchTool,
} from "./ops.js";
import {
  registerPortListTool,
  registerProcessKillTool,
  registerProcessListTool,
  registerStartProcessTool,
  registerStopProcessTool,
  registerTailLogTool,
  registerWaitForPortTool,
} from "./process.js";
import { registerScreenOcrTool, registerScreenScreenshotTool, registerWindowListTool } from "./screen.js";
import { registerShellTool } from "./shell.js";
import { registerWorkspaceInfoTool } from "./workspace.js";

type ToolDefinition = {
  category: "workspace" | "filesystem" | "shell" | "git" | "process" | "screen" | "desktop" | "browser";
  journalPolicy: "simple" | "operation" | "mutation";
  name: string;
  policyMode: PolicyMode;
  register: (server: McpServer, runtime: McpRuntime) => void;
  requiredScope: Scope;
  riskTags: readonly string[];
};

const TOOL_DEFINITION_ORDER = [
  "workspace_info",
  "stat",
  "list_dir",
  "tree",
  "search",
  "read_file",
  "read_many",
  "read_file_range",
  "stat_many",
  "hash",
  "write_file",
  "apply_patch",
  "mkdir",
  "copy",
  "move",
  "delete",
  "rollback_backup",
  "git_status",
  "git_diff",
  "git_commit",
  "start_process",
  "tail_log",
  "wait_for_port",
  "process_list",
  "port_list",
  "stop_process",
  "process_kill",
  "browser_session_create",
  "browser_navigate",
  "browser_snapshot",
  "browser_console",
  "browser_network",
  "browser_wait",
  "browser_click",
  "browser_fill",
  "browser_type",
  "browser_press_key",
  "browser_screenshot",
  "browser_page_list",
  "browser_page_select",
  "browser_session_list",
  "browser_session_close",
  "browser_cdp_connect",
  "window_list",
  "screen_screenshot",
  "screen_ocr",
  "desktop_mouse_position",
  "desktop_mouse_move",
  "desktop_mouse_click",
  "desktop_key_press",
  "desktop_hotkey",
  "desktop_text_type",
  "remote_worker_list",
  "remote_worker_health",
  "remote_worker_tools",
  "remote_worker_call",
  "shell",
] as const;

const TOOL_DEFINITION_RANK = new Map<string, number>(TOOL_DEFINITION_ORDER.map((name, index) => [name, index]));

const RAW_TOOL_DEFINITIONS = [
  {
    category: "workspace",
    journalPolicy: "simple",
    name: "workspace_info",
    policyMode: "observe",
    register: registerWorkspaceInfoTool,
    requiredScope: SCOPES.read,
    riskTags: [],
  },
  {
    category: "shell",
    journalPolicy: "operation",
    name: "shell",
    policyMode: "operate",
    register: registerShellTool,
    requiredScope: SCOPES.shell,
    riskTags: ["rce", "process", "network"],
  },
  {
    category: "filesystem",
    journalPolicy: "simple",
    name: "stat",
    policyMode: "observe",
    register: registerStatTool,
    requiredScope: SCOPES.read,
    riskTags: ["path-disclosure"],
  },
  {
    category: "filesystem",
    journalPolicy: "simple",
    name: "stat_many",
    policyMode: "observe",
    register: registerStatManyTool,
    requiredScope: SCOPES.read,
    riskTags: ["path-disclosure"],
  },
  {
    category: "filesystem",
    journalPolicy: "simple",
    name: "tree",
    policyMode: "observe",
    register: registerTreeTool,
    requiredScope: SCOPES.read,
    riskTags: ["path-disclosure"],
  },
  {
    category: "filesystem",
    journalPolicy: "simple",
    name: "list_dir",
    policyMode: "observe",
    register: registerListDirTool,
    requiredScope: SCOPES.read,
    riskTags: ["path-disclosure"],
  },
  {
    category: "filesystem",
    journalPolicy: "simple",
    name: "read_file_range",
    policyMode: "observe",
    register: registerReadFileRangeTool,
    requiredScope: SCOPES.read,
    riskTags: ["secret-read"],
  },
  {
    category: "filesystem",
    journalPolicy: "simple",
    name: "read_many",
    policyMode: "observe",
    register: registerReadManyTool,
    requiredScope: SCOPES.read,
    riskTags: ["secret-read"],
  },
  {
    category: "filesystem",
    journalPolicy: "simple",
    name: "hash",
    policyMode: "observe",
    register: registerHashTool,
    requiredScope: SCOPES.read,
    riskTags: ["content-fingerprint"],
  },
  {
    category: "filesystem",
    journalPolicy: "simple",
    name: "read_file",
    policyMode: "observe",
    register: registerReadFileTool,
    requiredScope: SCOPES.read,
    riskTags: ["secret-read"],
  },
  {
    category: "filesystem",
    journalPolicy: "mutation",
    name: "write_file",
    policyMode: "destructive",
    register: registerWriteFileTool,
    requiredScope: SCOPES.write,
    riskTags: ["file-write"],
  },
  {
    category: "filesystem",
    journalPolicy: "mutation",
    name: "copy",
    policyMode: "destructive",
    register: registerCopyTool,
    requiredScope: SCOPES.write,
    riskTags: ["file-write", "overwrite"],
  },
  {
    category: "filesystem",
    journalPolicy: "mutation",
    name: "mkdir",
    policyMode: "edit",
    register: registerMkdirTool,
    requiredScope: SCOPES.write,
    riskTags: ["filesystem-mutation"],
  },
  {
    category: "filesystem",
    journalPolicy: "mutation",
    name: "delete",
    policyMode: "destructive",
    register: registerDeleteTool,
    requiredScope: SCOPES.delete,
    riskTags: ["delete", "irreversible"],
  },
  {
    category: "filesystem",
    journalPolicy: "mutation",
    name: "move",
    policyMode: "destructive",
    register: registerMoveTool,
    requiredScope: SCOPES.write,
    riskTags: ["rename", "overwrite"],
  },
  {
    category: "filesystem",
    journalPolicy: "simple",
    name: "search",
    policyMode: "diagnose",
    register: registerSearchTool,
    requiredScope: SCOPES.read,
    riskTags: ["content-discovery"],
  },
  {
    category: "filesystem",
    journalPolicy: "operation",
    name: "rollback_backup",
    policyMode: "destructive",
    register: registerRollbackBackupTool,
    requiredScope: SCOPES.write,
    riskTags: ["rollback", "file-write"],
  },
  {
    category: "filesystem",
    journalPolicy: "operation",
    name: "apply_patch",
    policyMode: "destructive",
    register: registerApplyPatchTool,
    requiredScope: SCOPES.patch,
    riskTags: ["patch", "file-write"],
  },
  {
    category: "git",
    journalPolicy: "simple",
    name: "git_status",
    policyMode: "observe",
    register: registerGitStatusTool,
    requiredScope: SCOPES.git,
    riskTags: ["repo-state"],
  },
  {
    category: "git",
    journalPolicy: "simple",
    name: "git_diff",
    policyMode: "observe",
    register: registerGitDiffTool,
    requiredScope: SCOPES.git,
    riskTags: ["repo-content"],
  },
  {
    category: "git",
    journalPolicy: "operation",
    name: "git_commit",
    policyMode: "destructive",
    register: registerGitCommitTool,
    requiredScope: SCOPES.git,
    riskTags: ["commit", "repo-mutation"],
  },
  {
    category: "process",
    journalPolicy: "simple",
    name: "process_list",
    policyMode: "observe",
    register: registerProcessListTool,
    requiredScope: SCOPES.process,
    riskTags: ["process-disclosure"],
  },
  {
    category: "process",
    journalPolicy: "simple",
    name: "port_list",
    policyMode: "observe",
    register: registerPortListTool,
    requiredScope: SCOPES.process,
    riskTags: ["network-disclosure"],
  },
  {
    category: "process",
    journalPolicy: "simple",
    name: "wait_for_port",
    policyMode: "diagnose",
    register: registerWaitForPortTool,
    requiredScope: SCOPES.process,
    riskTags: ["network-probe"],
  },
  {
    category: "process",
    journalPolicy: "simple",
    name: "tail_log",
    policyMode: "observe",
    register: registerTailLogTool,
    requiredScope: SCOPES.process,
    riskTags: ["log-read"],
  },
  {
    category: "process",
    journalPolicy: "operation",
    name: "start_process",
    policyMode: "operate",
    register: registerStartProcessTool,
    requiredScope: SCOPES.process,
    riskTags: ["process", "rce", "long-running"],
  },
  {
    category: "process",
    journalPolicy: "operation",
    name: "stop_process",
    policyMode: "operate",
    register: registerStopProcessTool,
    requiredScope: SCOPES.process,
    riskTags: ["process-kill"],
  },
  {
    category: "process",
    journalPolicy: "operation",
    name: "process_kill",
    policyMode: "operate",
    register: registerProcessKillTool,
    requiredScope: SCOPES.process,
    riskTags: ["process-kill"],
  },
  {
    category: "screen",
    journalPolicy: "simple",
    name: "window_list",
    policyMode: "observe",
    register: registerWindowListTool,
    requiredScope: SCOPES.screen,
    riskTags: ["screen-disclosure", "window-title-disclosure"],
  },
  {
    category: "screen",
    journalPolicy: "operation",
    name: "screen_screenshot",
    policyMode: "diagnose",
    register: registerScreenScreenshotTool,
    requiredScope: SCOPES.screen,
    riskTags: ["screen-disclosure", "secret-read"],
  },
  {
    category: "screen",
    journalPolicy: "simple",
    name: "screen_ocr",
    policyMode: "diagnose",
    register: registerScreenOcrTool,
    requiredScope: SCOPES.screen,
    riskTags: ["screen-disclosure", "secret-read", "ocr"],
  },
  {
    category: "desktop",
    journalPolicy: "simple",
    name: "desktop_mouse_position",
    policyMode: "observe",
    register: registerDesktopMousePositionTool,
    requiredScope: SCOPES.desktop,
    riskTags: ["desktop-state", "mouse"],
  },
  {
    category: "desktop",
    journalPolicy: "operation",
    name: "desktop_mouse_move",
    policyMode: "operate",
    register: registerDesktopMouseMoveTool,
    requiredScope: SCOPES.desktop,
    riskTags: ["desktop-action", "mouse"],
  },
  {
    category: "desktop",
    journalPolicy: "operation",
    name: "desktop_mouse_click",
    policyMode: "operate",
    register: registerDesktopMouseClickTool,
    requiredScope: SCOPES.desktop,
    riskTags: ["desktop-action", "mouse", "click"],
  },
  {
    category: "desktop",
    journalPolicy: "operation",
    name: "desktop_key_press",
    policyMode: "operate",
    register: registerDesktopKeyPressTool,
    requiredScope: SCOPES.desktop,
    riskTags: ["desktop-action", "keyboard"],
  },
  {
    category: "desktop",
    journalPolicy: "operation",
    name: "desktop_hotkey",
    policyMode: "operate",
    register: registerDesktopHotkeyTool,
    requiredScope: SCOPES.desktop,
    riskTags: ["desktop-action", "keyboard", "hotkey"],
  },
  {
    category: "desktop",
    journalPolicy: "operation",
    name: "desktop_text_type",
    policyMode: "operate",
    register: registerDesktopTextTypeTool,
    requiredScope: SCOPES.desktop,
    riskTags: ["desktop-action", "keyboard", "form-input"],
  },
  {
    category: "browser",
    journalPolicy: "operation",
    name: "browser_cdp_connect",
    policyMode: "operate",
    register: registerBrowserCdpConnectTool,
    requiredScope: SCOPES.browser,
    riskTags: ["browser", "cdp", "existing-profile", "secret-read"],
  },
  {
    category: "browser",
    journalPolicy: "operation",
    name: "browser_session_create",
    policyMode: "operate",
    register: registerBrowserSessionCreateTool,
    requiredScope: SCOPES.browser,
    riskTags: ["browser", "network", "process"],
  },
  {
    category: "browser",
    journalPolicy: "simple",
    name: "browser_session_list",
    policyMode: "observe",
    register: registerBrowserSessionListTool,
    requiredScope: SCOPES.browser,
    riskTags: ["browser-state"],
  },
  {
    category: "browser",
    journalPolicy: "operation",
    name: "browser_session_close",
    policyMode: "operate",
    register: registerBrowserSessionCloseTool,
    requiredScope: SCOPES.browser,
    riskTags: ["browser", "process"],
  },
  {
    category: "browser",
    journalPolicy: "simple",
    name: "browser_page_list",
    policyMode: "observe",
    register: registerBrowserPageListTool,
    requiredScope: SCOPES.browser,
    riskTags: ["browser-state", "secret-read"],
  },
  {
    category: "browser",
    journalPolicy: "operation",
    name: "browser_page_select",
    policyMode: "operate",
    register: registerBrowserPageSelectTool,
    requiredScope: SCOPES.browser,
    riskTags: ["browser-state"],
  },
  {
    category: "browser",
    journalPolicy: "operation",
    name: "browser_navigate",
    policyMode: "operate",
    register: registerBrowserNavigateTool,
    requiredScope: SCOPES.browser,
    riskTags: ["browser", "network"],
  },
  {
    category: "browser",
    journalPolicy: "simple",
    name: "browser_snapshot",
    policyMode: "observe",
    register: registerBrowserSnapshotTool,
    requiredScope: SCOPES.browser,
    riskTags: ["browser-content", "secret-read"],
  },
  {
    category: "browser",
    journalPolicy: "operation",
    name: "browser_click",
    policyMode: "operate",
    register: registerBrowserClickTool,
    requiredScope: SCOPES.browser,
    riskTags: ["browser-action"],
  },
  {
    category: "browser",
    journalPolicy: "operation",
    name: "browser_fill",
    policyMode: "operate",
    register: registerBrowserFillTool,
    requiredScope: SCOPES.browser,
    riskTags: ["browser-action", "form-input"],
  },
  {
    category: "browser",
    journalPolicy: "operation",
    name: "browser_type",
    policyMode: "operate",
    register: registerBrowserTypeTool,
    requiredScope: SCOPES.browser,
    riskTags: ["browser-action", "form-input"],
  },
  {
    category: "browser",
    journalPolicy: "operation",
    name: "browser_press_key",
    policyMode: "operate",
    register: registerBrowserPressKeyTool,
    requiredScope: SCOPES.browser,
    riskTags: ["browser-action", "keyboard"],
  },
  {
    category: "browser",
    journalPolicy: "simple",
    name: "browser_wait",
    policyMode: "diagnose",
    register: registerBrowserWaitTool,
    requiredScope: SCOPES.browser,
    riskTags: ["browser-state"],
  },
  {
    category: "browser",
    journalPolicy: "operation",
    name: "browser_screenshot",
    policyMode: "diagnose",
    register: registerBrowserScreenshotTool,
    requiredScope: SCOPES.browser,
    riskTags: ["browser-content", "secret-read", "screenshot"],
  },
  {
    category: "browser",
    journalPolicy: "simple",
    name: "browser_console",
    policyMode: "observe",
    register: registerBrowserConsoleTool,
    requiredScope: SCOPES.browser,
    riskTags: ["browser-content", "log-read"],
  },
  {
    category: "browser",
    journalPolicy: "simple",
    name: "browser_network",
    policyMode: "observe",
    register: registerBrowserNetworkTool,
    requiredScope: SCOPES.browser,
    riskTags: ["browser-content", "network-disclosure"],
  },
  {
    category: "process",
    journalPolicy: "simple",
    name: "remote_worker_list",
    policyMode: "observe",
    register: registerRemoteWorkerListTool,
    requiredScope: SCOPES.process,
    riskTags: ["read-only", "remote-worker"],
  },
  {
    category: "process",
    journalPolicy: "simple",
    name: "remote_worker_health",
    policyMode: "observe",
    register: registerRemoteWorkerHealthTool,
    requiredScope: SCOPES.process,
    riskTags: ["read-only", "remote-worker"],
  },
  {
    category: "process",
    journalPolicy: "simple",
    name: "remote_worker_tools",
    policyMode: "observe",
    register: registerRemoteWorkerToolsTool,
    requiredScope: SCOPES.process,
    riskTags: ["read-only", "remote-worker"],
  },
  {
    category: "process",
    journalPolicy: "simple",
    name: "remote_worker_call",
    policyMode: "observe",
    register: registerRemoteWorkerCallTool,
    requiredScope: SCOPES.process,
    riskTags: ["read-only", "remote-worker"],
  },
] as const satisfies ReadonlyArray<ToolDefinition>;

export type ToolName = (typeof RAW_TOOL_DEFINITIONS)[number]["name"];

export const TOOL_DEFINITIONS: ReadonlyArray<(typeof RAW_TOOL_DEFINITIONS)[number]> = [...RAW_TOOL_DEFINITIONS].sort(
  (a, b) => (TOOL_DEFINITION_RANK.get(a.name) ?? Number.MAX_SAFE_INTEGER) - (TOOL_DEFINITION_RANK.get(b.name) ?? Number.MAX_SAFE_INTEGER),
);

export const TOOL_SCOPES: Readonly<Record<ToolName, Scope>> = Object.fromEntries(
  TOOL_DEFINITIONS.map((tool) => [tool.name, tool.requiredScope]),
) as Record<ToolName, Scope>;

export function requiredScopeForTool(toolName: string): Scope | undefined {
  return (TOOL_SCOPES as Partial<Record<string, Scope>>)[toolName];
}

export function definitionForTool(toolName: string): ToolDefinition | undefined {
  return TOOL_DEFINITIONS.find((tool) => tool.name === toolName);
}

export function registerAllTools(server: McpServer, runtime: McpRuntime): void {
  for (const tool of TOOL_DEFINITIONS) {
    tool.register(server, runtime);
  }
}
